#!/usr/bin/env node

const { execSync } = require('child_process');
const path = require('path');

execSync(`node ./console/signal.js ${[...process.argv.slice(2)].join(' ')}`, { cwd: path.resolve('./') });
